blank_issues_enabled: false
contact_links:
  - name: New Idea
    url: https://github.com/the-ge/thege.hodgepodge.launcher/discussions/new?category=ideas
    about: Suggest an idea to improve PrestaShop
